language: haxe

haxe:
  - "3.2.1"
  - development

install:
  - git clone --recursive https://github.com/DoclerLabs/hexCore.git ~/hexcore

script:
  - haxe build-js.hxml           && node bin/MainUnitTest.js
  
notifications:
  email:
    recipients:
      - francis_bourre@me.com
      - peterphonix@gmail.com