sudo: required
dist: trusty

language: haxe

# haxe versions : http://haxe.org/website-content/downloads/versions.json
haxe:
  - "3.4.7"
  - development

matrix:
  allow_failures:
  - haxe: development

before_install:
  - echo $TRAVIS_BRANCH
  - export DEPENDENCIES_BRANCH=$TRAVIS_BRANCH
  - echo $TRAVIS_TAG
  - if [[ "$TRAVIS_TAG" != "" ]]; then export DEPENDENCIES_BRANCH=$TRAVIS_TAG; fi
  - echo $DEPENDENCIES_BRANCH

install:
  - haxelib newrepo
  - export BRANCH_REF=$DEPENDENCIES_BRANCH
  - haxelib install travix --always
# hexLog
  - if [ $( git ls-remote https://github.com/DoclerLabs/hexLog.git $BRANCH_REF --heads | wc -l ) == "0" ]; then export DEPENDENCIES_BRANCH=master; else export DEPENDENCIES_BRANCH=$BRANCH_REF; fi
  - echo Checking out $DEPENDENCIES_BRANCH
  - git clone --recursive -b $DEPENDENCIES_BRANCH https://github.com/DoclerLabs/hexLog.git ./hexlog
  - haxelib dev hexlog ./hexlog
# hexCore
  - if [ $( git ls-remote https://github.com/DoclerLabs/hexCore.git $BRANCH_REF --heads | wc -l ) == "0" ]; then export DEPENDENCIES_BRANCH=master; else export DEPENDENCIES_BRANCH=$BRANCH_REF; fi
  - echo Checking out $DEPENDENCIES_BRANCH
  - git clone --recursive -b $DEPENDENCIES_BRANCH https://github.com/DoclerLabs/hexCore.git ./hexcore
  - haxelib install ./hexcore/haxelib.json --always
  - haxelib dev hexcore ./hexcore
#hexUnit
  - haxelib dev hexunit .

script:
  - haxelib run travix php
  - haxelib run travix neko
  - haxelib run travix js
  - haxelib run travix flash -swf-version 10.1 -D swf-script-timeout=180
  - if [ $TRAVIS_HAXE_VERSION == development ]; then haxelib run travix hl; fi
  
notifications:
  email:
    recipients:
      - francis_bourre@me.com
      - peterphonix@gmail.com
      - laurent@geturl.net
